services:
  - type: web
    name: munajiz
    runtime: python
    buildCommand: pip install -r Requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: PORT
        value: 10000
